config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :websites, path: '' do
    resources :elements, controller: 'website_content/elements'
  end

  resources :elements, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :website

  str_enum :element_type, %i[string image div]
end

app/models/website.rb
class Website < ApplicationRecord
  has_many :elements, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def update
    @element = Element.find(params[:element_id] || params[:id])

    @element.update element_params
  end

  private

  def element_params
    params.require(:element).permit(:type, :x, :y)
  end
end

app/controllers/website_content/base_controller.rb
module WebsiteContent
  class BaseController < ApplicationController
    before_action :set_website

    private

    def set_website
      @website = Website.find(params[:website_id])
    end
  end
end

app/controllers/website_content/elements_controller.rb
module WebsiteContent
  class ElementsController < BaseController
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token

    before_action :set_element, only: %i[edit update show destroy test_element]

    def new
      @element = @website.elements.new
    end

    def create
      @element = @website.elements.new element_params
      if @element.save
        redirect_to website_path(@website)
      else
        render :new
      end
    end

    def edit; end

    def update
      if @element.update element_params
        redirect_to website_path(@website)
      else
        render :edit
      end
    end

    def destroy
      @element.destroy
      redirect_to website_path(@website)
    end

    private

    def element_params
      params.require(:element).permit(:element_type, :x, :y)
    end

    def set_element
      @element = @website.elements.find(params[:element_id] || params[:id])
    end
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: %i[edit update destroy show]

  def index
    @websites = Website.all
  end

  def new
    @website = Website.new
  end

  def create
    @website = Website.new website_params
    if @website.save
      redirect_to '/'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @website.update website_params
      redirect_to '/'
    else
      render :edit
    end
  end

  def destroy
    @website.destroy
    redirect_to '/'
  end

  def show; end

  private

  def website_params
    params.require(:website).permit(:name)
  end

  def set_website
    @website = Website.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebBuilder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <%= vite_javascript_tag 'application' %>
    <%= vite_client_tag %>
  </head>

  <body data-turbo="false">
    <%= turbo_frame_tag 'modal' %>

    <main class="flex h-screen overflow-hidden bg-slate-200">
      <div class="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/website_content/elements/_form.html.erb
<%= f.select :element_type, collection: Element.element_types %>
<button>Create</button>

app/views/website_content/elements/edit.html.erb
<%= simple_form_for @element, url: website_element_path(@website, @element) do |f| %>
  <%= render TurboModalComponent.new(title: '') do %>
    <%= render 'form', f: f %>
  <% end %>
<% end %>

app/views/website_content/elements/new.html.erb
<%= render TurboModalComponent.new(title: '') do %>
  <%= simple_form_for @element, url: website_elements_path(@website) do |f| %>
    <%= render 'form', f: f %>
  <% end %>
<% end %>

app/views/website_content/elements/types/_div.html.erb
<div class="hover:cursor-grabbing absolute bg-slate-50"
     data-controller="elements--interact"
     data-elements--interact-target="element"
     data-elements--interact-element-id-value="<%= element.id %>"
     data-elements--interact-website-id-value="<%= element.website.id %>"
     data-elements--interact-element-object-value="<%= element.attributes.to_json %>"
     style="width: 100%; height: 960px; top: <%= element.y %>px; left: <%= element.x %>px">
  Div
</div>

app/views/website_content/elements/types/_string.html.erb
<div class="hover:cursor-grabbing absolute"
     data-controller="elements--interact"
     data-elements--interact-target="element"
     data-elements--interact-element-id-value="<%= element.id %>"
     data-elements--interact-website-id-value="<%= element.website.id %>"
     data-elements--interact-element-object-value="<%= element.attributes.to_json %>"
     style="top: <%= element.y %>px; left: <%= element.x %>px">
  <span>Text</span>
</div>

app/views/websites/_form.html.erb
<%= f.input :name %>
<%= f.submit %>

app/views/websites/edit.html.erb
<%= simple_form_for @website, url: website_path(@website) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/websites/index.html.erb
<div class="w-full space-y-5 p-5">
  <%= link_to 'new website', new_website_path() %>
  <div class="space-y-3 bg-white rounded-lg p-5">
    <% @websites.each do |website| %>
      <div class="flex justify-between w-full w-1/3">
        <%= link_to website.name, website_path(website) %>
        <div class="flex space-x-3">
          <%= link_to 'show', website_path(website) %>
          <%= link_to 'edit', edit_website_path(website) %>
          <%= button_to 'destroy', website_path(website), method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/websites/new.html.erb
<%= simple_form_for @website, url: websites_path do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/websites/show.html.erb
<%= link_to 'new element', new_website_element_path(@website), data: { turbo: true, turbo_frame: 'modal'}, class: 'absolute right-5 z-50' %>

<div class="min-w-screen min-h-screen relative">
  <% @website.elements.each do |element| %>
    <%= render "website_content/elements/types/#{element.element_type}", element: element %>
  <% end %>
</div>